name: iOS CI Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Run Unit Tests
        run: xcodebuild test -scheme "ListPhoto" -project "ListPhoto.xcodeproj" -destination 'platform=iOS Simulator,name=iPhone 14'
